control_dict = ("/*--------------------------------*- C++ -*----------------------------------*\\\n"
				"  =========       \n"
				"  \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox\n"
				"   \\\\    /   O peration     | Website:  https://openfoam.org\n"
				"    \\\\  /    A nd           | Version:  6\n"
				"     \\\\/     M anipulation  |""\n"
				"\\*---------------------------------------------------------------------------*/"
				"\n"
				"FoamFile\n"
				"{\n"
				"	version     2.0;\n"	
				"	format      ascii;\n"
				"	class       dictionary;\n"
				"	object      controlDict;\n"
				"}\n"
				"// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n"
				"\n"
				"application	\tporousSimpleFoam;\n\n"
				"startFrom		latestTime;\n\n"
				"startTime		0;\n\n"
				"stopAt			endTime;\n\n"
				"endTime			2000;\n\n"
				"deltaT			1;\n\n"
				"writeControl	timeStep;\n\n"
				"writeInterval	250;\n\n"
				"purgeWrite		2;\n\n"
				"writeFormat	\tbinary;\n\n"
				"writePrecision	6;\n\n"
				"writeCompression off;\n\n"
				"timeFormat		general;\n\n"
				"timePrecision	6;\n\n"
				"runTimeModifiable true;\n\n"
				"functions\n"
				"{\n"
				#"	sTransport\n"
				#"	{\n"
				#"		type			energyTransport;\n"
				#"		libs			('"'libsolverFunctionObjects.so'"')\n\n"
				#"		enabled			true;\n"
				#"		writeControl	outputTime;\n"
				#"		writeInterval	1;\n\n"
				#"		field			T;\n\n"
				#"		phi				phi;\n\n"
				#"		// Thermal properties\n"
				#"		Cp 				Cp 		[j/kg/K]	1006;\n"
				#"		kappa			kappa	[W/m/K]		0.02587;\n"
				#"		rhoInf			rho 	[kg/m^3]	1;\n\n"
				#"		write   		true;\n\n"
				#"		fvOptions\n"
				#"		{\n"
				#"			viscousDissipation\n"
				#"			{\n"
				#"				type			viscousDissipation;\n"
				#"				enabled 		true;\n\n"
				#"				viscousDissipationCoeffs\n"
				#"				{\n"
				#"					fields		(T);\n"
				#"					rhoInf		$....rhoInf;\n"
				#"				}\n"
				#"			}\n"
				#"		}\n"
				#"	}\n"
				"#include '"'forceCoeffs'"'\n"
				"#include '"'force'"'\n"
				"}\n\n"
				"libs (\n"
				"'"'libOpenFOAM.so'"'\n"
				"'"'libsimpleSwakFunctionObjects.so'"'\n"
				"'"'libswakFunctionObjects.so'"'\n"
				"'"'libgroovyBC.so'"'\n"
				");\n")

