fvSolution = ("/*--------------------------------*- C++ -*----------------------------------*\\\n"
				"  =========       \n"
				"  \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox\n"
				"   \\\\    /   O peration     | Website:  https://openfoam.org\n"
				"    \\\\  /    A nd           | Version:  6\n"
				"     \\\\/     M anipulation  |""\n"
				"\\*---------------------------------------------------------------------------*/"
				"\n"
				"FoamFile\n"
				"{\n"
				"	version     2.0;\n"	
				"	format      ascii;\n"
				"	class       dictionary;\n"
				"	object      fvSolution;\n"
				"}\n"
				"// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n\n"
				"solvers\n"
				"{\n"
				"	p\n"
				"		solver			GAMG;\n"
				"		smoother		GaussSeidel;\n"
				"		tolerance		1e-5;\n"
				"		relTol			0.01;\n"
				"}\n\n"
				"	omega\n"
				"	{\n"
				"		solver			smoothSolver;\n"
				"		smoother		symGaussSeidel;\n"
				"		tolerance		1e-6;\n"
				"		relTol			0.1;\n"
				"	}\n\n"
				"	U\n"
				"	{\n"
				"		solver			smoothSolver;\n"
				"		smoother		GaussSeidel;\n"
				"		tolerance		1e-8;\n"
				"		relTol			0;\n"
				"		nSweeps			1;\n"
				"	}\n\n"
				"	\"(k|omega|h|T)\"\n"
				"	{\n"
				"		solver			smoothSolver;\n"
				"		smoother		GaussSeidel;\n"
				"		nSweeps			2;\n"
				"		tolerance		1e-6;\n"
				"		relTol			0.1;\n"
				"	}\n\n"
				"	\"(U|k|omega|T)Final\"\n"
				"	{\n"
				"		$U;\n"
				"		tolerance		1e-6;\n"
				"		relTol			0.1;\n"
				"	}\n\n"
				"SIMPLE\n"
				"{\n"
				"	nUCorrectors        2;\n"
				"	nNonOrthogonalCorrectors 0;\n"
				"	pMinFactor          0.5;\n"
				"	pMaxFactor          2.0;\n\n"
				"	residualControl\n"
				"	{\n"
				"		p 				1e-3;\n"
				"		U 				1e-4;\n"
				"		omega 			1e-3;\n"
				"		// possibly check turbulence fields\n"
				"		\"(k|epsilon|omega|T)\" 1e-3;\n"
				"	}\n"
				"}\n"
				"relaxationFactors\n"
				"{\n"
				"	fields\n"
				"	{\n"
				"		p 				0.3;\n"
				"	}\n"
				"	equations\n"
				"	{\n"
				"		U 				0.7;\n"
				"		k 				0.7;\n"
				"		omega 			0.7;\n"
				"		T   			0,7;\n"
				"	 }\n"
				"}\n"
				"// ************************************************************************* //")
