prsty_prop = (    "/*--------------------------------*- C++ -*----------------------------------*\\\n"
                "  =========       \n"
                "  \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox\n"
                "   \\\\    /   O peration     | Website:  https://openfoam.org\n"
                "    \\\\  /    A nd           | Version:  6\n"
                "     \\\\/     M anipulation  |""\n"
                "\\*---------------------------------------------------------------------------*/"
                "\n"
                "FoamFile\n"
                "{\n"
                "    version     2.0;\n"
                "    format      ascii;\n"
                "    class       dictionary;\n"
                "    location    constant;\n"
                "    object      porosityProperties;\n"
                "}\n"
                "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n\n"
                "porosity1\n"
                "{\n"
                "    type        DarcyForchheimer;\n\n"
                "    cellZone    ws;\n\n"
                "    d    (0 0 0);\n"
                "    f   (0 0 0);\n\n"
                "    coordinateSystem\n"
                "    {\n"
                "        type    cartesian;\n"
                "        origin    (0 0 0);\n"
                "        coordinateRotation\n"
                "        {\n"
                "            type    axesRotation;\n"
                "            e1        (0 0 1);\n"
                "            e2        (1 0 0);\n"
                "        }\n"
                "    }\n"
                "}\n"
                "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //"
            )
