import global_variables
turb_prop = (	"/*--------------------------------*- C++ -*----------------------------------*\\\n"
				"  =========       \n"
				"  \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox\n"
				"   \\\\    /   O peration     | Website:  https://openfoam.org\n"
				"    \\\\  /    A nd           | Version:  6\n"
				"     \\\\/     M anipulation  |""\n"
				"\\*---------------------------------------------------------------------------*/"
				"\n"
				"FoamFile\n"
				"{\n"
				"	version     2.0;\n"	
				"	format      ascii;\n"
				"	class       dictionary;\n"
				"	location	constant;\n"
				"	object      turbulenceProperties;\n"
				"}\n"
				"// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n\n"
				"simulationType RAS;\n\n"
				"RAS"
				"{\n"
				f"	RASModel		{global_variables.incompressible_ras_turbulence_model_name};\n\n"
				"	turbulence				on;\n\n"
				"	printCoeffs				on;\n"
				"}\n"	
				"// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //"
			)
